### ISSUE TITLE
Unification of docker file names

### ISSUE THREAD

**Issue by jkbk2004** [NOAA-EPIC/ufs-containers#3]
As work in progress for Jekins hooks to git actions, this is a good opportunity to generalize the docker file names:
1. three docker files are contained in this repo
2. ubuntu20.04-gnu9.3.docker, ubuntu20.04-gnu9.3-hpc-stack.docker, ubuntu20.04-ufs-srwapp.docker

Is [OS]-[Compiler]-ufs-[App].dokcer the way to go? Can we add some opinions about the topic on this issue? So we can move on for PRs.

**Comment by EdwardSnyder-NOAA** [comment]
I see no issue with this naming convention. My one suggestion would be to incorporate the 'ufs' into the [App] name, so when we build the hcp-stack container it would be ubuntu20.04-gnu9.3-hpc-stack.docker and not ubuntu20.04-gnu9.3-ufs-hpc-stack.docker. The former seems less confusing.

**Comment by jessemcfarland** [comment]
The other question I raised is whether `gnu9.3` should be incorporated in the application container names, e.g. `ubuntu20.04-gnu9.3-ufs-srwapp`. I think this make sense if we're anticipating an intel version of the container at some point in the future.

**Comment by jessemcfarland** [comment]
We may also want to consider updating the file names to `container.Dockerfile` or `Dockerfile.container` to follow docker naming conventions: https://docs.docker.com/engine/reference/commandline/build/#specify-a-dockerfile--f.
